# How many seconds the combat lasts for
combat-timer: 15

on-combat:
  # disables both users flight on combat
  disable-flight: true

  # forces gamemode
  force-gamemode: survival # leave empty to disable
  force-gamemode-message: '&c7Your gamemode has been updated.'

protected-regions:
  message: '&7You cannot enter this region while in combat.'
  # interval between sending messages, so it doesnt spam the users feed.
  interval: 5
  #  regions:
  #    - 'spawn'

  # List of blacklisted worlds that combat wont work in
blacklisted-worlds:
#  - world_nether

# List of blacklisted commands that cannot be used in combat
blacklisted-commands:
#  - tp

# Message issued when player uses a blacklisted command in combat
blacklisted-command-message: '&7You cannot run this command while in combat!'

chat:
  # The message for going into combat (CHAT)
  on-message: '&7You are now in &6ombat!'

  # The message for going out of combat (CHAT)
  off-message: '&7You are now out of &6combat!'

  # If the plugin will use chat messages
  # If false it will still print when the players dies during combat
  use: true

actionbar:
  # The message for going into combat (ACTIONBAR)
  on-message: '&cYou are now in combat for %combatlogger_timeformatted%!'

  # The message for going out of combat (ACTIONBAR)
  off-message: '&cYou are now out of combat!'

  # If the plugin will use actionbar messages
  use: true

# The punishment activates when a user logs out during combat
# Types: "KILL", "BAN:TIMEINSECONDS:REASON`{timeRemaining}=CURRENTBANTIME`, "WHITELIST""
# To remove a punishment just remove the line examaple,
# this will only kill the player when they log out during combat
#-----------
# punishment:
#   - "KILL"
#-----------
#To disable punishments you can do `punishments: []`
punishment:
  - "BAN:10:&cYou logged out during combat \n Please wait %combatlogger_timeformatted%"
  - "KILL"