# Checks if the plugin is up to date
UpdateChecker: true

Permissions:
  Default:
    Message:
      MessageOn: '&cOn'
      MessageOff: '&aOff'
    Actionbar:
      MessageOn: '&5Action ON'
      MessageOff: '&5Combat off'
    Time: 15
    Punishment:
      KILL: [ ]
      BAN:
        Message: "&cBuy a &fRANK &cto shorten ban time"
        Time: 60
  VIP:
    Weight: 5
    Time: 5
    Message:
      MessageOn: '&cOn #P2'
      MessageOff: '&aOff #P2W'
    Actionbar:
      MessageOn: '&5Action ON #P2W'
      MessageOff: '&5Combat off #P2W'
    Permission: "combatlogger.vip"
    Punishment:
      BAN:
        Message: "&f#P2W!"
        Time: 10

punishment:
  ban:
    message: "&cYou logged out during combat \n Please wait %combatlogger_timeformatted%"
    time: 10000
  kill: [ ]