# Specifies the duration of combat in seconds
combat-timer: 15

chat:
  # Message displayed when a player enters combat in chat
  on-message: '&fYou are now in &6combat&f!'

  # Message displayed when a player leaves combat in chat
  off-message: '&fYou are now out of &6combat&f!'

  # Whether the plugin will use chat messages
  use: true

actionbar:
  # Message displayed when a player enters combat in the action bar
  on-message: '&6You are now in &fcombat &7for %combatlogger_timeformatted%!'

  # Message displayed when a player leaves combat in the action bar
  off-message: '&6You are now out of &fcombat&f!'

  # Whether the plugin will use action bar messages
  use: true

# Specifies punishments for players who log out during combat.
# Punishments can include various types:
# - "BAN:10:&cYou logged out during combat \n Please wait %combatlogger_timeformatted%": Temporarily bans the player for 10 seconds with a custom reason,
#   informing them to wait for the specified combat timer duration.
# - "KILL": Kills the player upon logging out during combat.
# - "ECO:-1500:&7Your balance has been reduced by &c$1500 &7for logging out during combat.": Deducts $1500 from the player's in-game account
#   as a penalty for logging out during combat.
# - "COMMAND:broadcast &c%player% logged out during combat :(": Executes a broadcast command, notifying all players that the specified player
#   logged out during combat.
punishment:
  - "BAN:10:&fYou logged out during &6combat &7\n Please wait %combatlogger_timeformatted%"
  - "KILL"
#  - "ECO:-1500:&fYour balance has been reduced by &6$1500 &7for logging out during combat."
#  - "COMMAND:broadcast &6%player% &flogged out during combat :("

on-combat:
  # Disables flight for players in combat
  disable-flight: true

  # Forces players into a specific gamemode during combat
  force-gamemode: survival # Leave empty to disable
  force-gamemode-message: '&6Your gamemode has been updated.'

protected-regions:
  # Message displayed when players attempt to enter protected regions while in combat
  message: '&fYou cannot enter this region while in &6combat&f.'
  # Interval between sending messages to avoid spamming players' chat feed
  interval: 10
#  regions:
#    - spawn

# List of worlds where combat is disabled
blacklisted-worlds:
# - world_nether

# List of commands disabled during combat
blacklisted-commands:
# - tp

# Message displayed when a player attempts to use a blacklisted command during combat
blacklisted-command-message: '&fYou cannot &crun&f this command while in &6combat&f!'