combat-timer: 15
combat-walls:
  enabled: true
  regions:
    spawn:
      enabled: true
      wall-material: RED_STAINED_GLASS
      wall-height: 4
      wall-segment-length: 4
      border-proximity: 4
      update-throttle-ms: 100
      ground-anchor-range: 5
      
chat:
  enabled: true
  interval:
    seconds:
      - 10
      - 5
    message: '&fCombat time remaining &c%combatlogger_timeformatted%'
  on-message: '&fYou are now in &ccombat&f.'
  off-message: '&fYou are no longer in &ccombat&f.'

actionbar:
  enabled: true
  interval: 0
  on-message: '&fIn combat &c%combatlogger_timeformatted%'
  off-message: '&fYou are no longer in combat.'

on-combat:
  disable-flight: true
  disable-elytra: false
  disable-ender-pearls: false
  force-gamemode:
    mode: SURVIVAL
    message: '&fYour gamemode was changed.'

ignored-projectiles:
  - EGG
  - ENDER_PEARL
  - SNOWBALL

protected-regions:
  message: '&fYou cannot enter this region while in combat.'
  interval: 10
  regions:
    - spawn

blacklisted-worlds:
  - world_nether

blacklisted-commands:
  - tp
  - home
  - spawn
  - fly

blacklisted-command-message: '&fYou cannot use this command while in combat.'