# Specifies the duration of combat in seconds
combat-timer: 15

on-combat:
  # Disables flight for players in combat
  disable-flight: true

  # Forces players into a specific gamemode during combat
  force-gamemode: survival # Leave empty to disable
  force-gamemode-message: '&cYour gamemode has been updated.'

protected-regions:
  # Message displayed when players attempt to enter protected regions while in combat
  message: '&7You cannot enter this region while in combat.'
  # Interval between sending messages to avoid spamming players' chat feed
  interval: 10
#  regions:
#    - spawn

# List of worlds where combat is disabled
blacklisted-worlds:
# - world_nether

# List of commands disabled during combat
blacklisted-commands:
# - tp

# Message displayed when a player attempts to use a blacklisted command during combat
blacklisted-command-message: '&7You cannot run this command while in combat!'

chat:
  # Message displayed when a player enters combat in chat
  on-message: '&7You are now in combat!'

  # Message displayed when a player leaves combat in chat
  off-message: '&7You are now out of combat!'

  # Whether the plugin will use chat messages
  use: true

actionbar:
  # Message displayed when a player enters combat in the action bar
  on-message: '&cYou are now in combat for %combatlogger_timeformatted%!'

  # Message displayed when a player leaves combat in the action bar
  off-message: '&cYou are now out of combat!'

  # Whether the plugin will use action bar messages
  use: true

# Specifies punishments for players who log out during combat
# Punishments can be one or more of the following types:
# "KILL", "BAN:TIMEINSECONDS:REASON`{timeRemaining}=CURRENTBANTIME", "WHITELIST"
# "ECO:-100" deducts $100 from the player's account using Vault integration
# To disable punishments, leave the line empty, e.g., punishments: []
punishment:
  - "BAN:10:&cYou logged out during combat \n Please wait %combatlogger_timeformatted%"
  - "KILL"
  - "ECO:-1500:&7Your balance has been reduced by &c$1500 &7for logging out during combat."
  - "COMMAND:/op"