name: CombatLogger
version: '${project.version}'
main: com.keurig.combatlogger.CombatLogger
authors: [ Keurig ]
description: A simple combat logger plugin!
api-version: 1.13
softdepend:
  - Factions
  - PlaceholderAPI
  - WorldGuard
permissions:
  combatlogger.admin:
    default: false
    description: Allows bypassing combat tag restrictions.
  combatlogger.command:
    default: false
    description: Allows usage of the default command to reload the plugin's configuration.

commands:
  combatlogger:
    description: Main command for managing CombatLogger plugin.
    aliases:
      - cl
      - comblog
    permissions:
      - combatlogger.command